### PR TITLE
Rename action support for power pages entities

### PR DESCRIPTION
**Pull request by tyaginidhi**
RenameFilesDesktopExtesnsion

Update: Fixed the issues in page-template, and polls entity adx_name updates

TODO: Need to add telemetry and localization updates
Verify yml file field updates for each entity

### CODE REVIEW

**Comment by amitjoshi438** [comment]
We may need to check once; our name formatting is in parity with PAC otherwise on download they will be overwritten.

**Comment by amitjoshi438** [comment]
We may need to check once; our name formatting is in parity with PAC otherwise on download they will be overwritten.

**Comment by amitjoshi438** [comment]
In case of webfile the key **filename** remains same?

**Review by amitjoshi438 — APPROVED** [review]

**Review by ashishchoudhary001 — APPROVED** [review]

**Comment by tyaginidhi** [comment]
> 

Yeah. that is correct. For webfile the adx_name param has the complete filename like ABC.png, XYZ.mp4 etc. For other entities it varies, and thats where we need to update adx_name update function. I have noticed / and . and - and spaces being set in adx_name.

**Pull request merged**
